// Generates the three PWA icons referenced by `app/manifest.ts`:
//   public/icons/icon-192.png         — 192x192 standard
//   public/icons/icon-512.png         — 512x512 standard
//   public/icons/icon-maskable-512.png — 512x512 with safe-area padding
//
// The visual is a flat brand-green tile with the rub-el-hizb glyph (۞) — the
// same Islamic ornament used as the wordmark fallback throughout the app.
// Output is rendered from a hand-coded SVG via `sharp`, which already ships
// as a transitive dependency through Next 16 (no new package needed).
//
// Run with: npm run gen:icons
// Re-run any time the brand colour or glyph changes.

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

// Brand tokens from app/globals.css. Keep in sync if those change.
const BRAND_GREEN = "#7ba143";
const GLYPH_WHITE = "#ffffff";

// SVG source. The viewBox is 512 — sharp resizes to whatever the caller asks.
// `dominant-baseline="central"` + `text-anchor="middle"` centres the glyph
// optically; `font-size` is tuned to fill ~62% of the standard tile, leaving
// breathing room and matching what most launcher icons do.
function svg({
  size,
  bg,
  fg,
  glyphScale,
}: {
  size: number;
  bg: string;
  fg: string;
  glyphScale: number;
}): string {
  const fontSize = Math.round(size * glyphScale);
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <rect width="${size}" height="${size}" fill="${bg}"/>
  <text
    x="50%"
    y="50%"
    text-anchor="middle"
    dominant-baseline="central"
    font-family="'Segoe UI Symbol', 'Noto Sans Symbols', sans-serif"
    font-size="${fontSize}"
    fill="${fg}"
  >۞</text>
</svg>`;
}

async function render(size: number, glyphScale: number, outFile: string) {
  const buffer = Buffer.from(
    svg({ size, bg: BRAND_GREEN, fg: GLYPH_WHITE, glyphScale }),
  );
  await sharp(buffer).png().toFile(outFile);
  console.log(`wrote ${outFile} (${size}×${size})`);
}

async function main() {
  const outDir = path.resolve(process.cwd(), "public/icons");
  await mkdir(outDir, { recursive: true });

  // Standard icons fill the tile ~62%.
  await render(192, 0.62, path.join(outDir, "icon-192.png"));
  await render(512, 0.62, path.join(outDir, "icon-512.png"));

  // Maskable icons need the meaningful content to fit inside the 80% safe
  // area (centred 0.4r circle for circular masks). We shrink the glyph and
  // keep the full-bleed background, so circular launcher masks crop only
  // the green and never the symbol.
  await render(512, 0.42, path.join(outDir, "icon-maskable-512.png"));

  // Marker file so future devs see where the icons came from. Tiny, no risk.
  const readme = `# PWA icons

Generated by \`scripts/generate-icons.ts\`. Re-run with:

    npm run gen:icons

The script renders a brand-green tile with the rub-el-hizb glyph (۞) at the
sizes referenced in [app/manifest.ts](../../app/manifest.ts). Replace these
PNGs with designer-supplied artwork when available — keep the same filenames
so the manifest doesn't need editing.
`;
  await writeFile(path.join(outDir, "README.md"), readme);
}

main().catch((err) => {
  console.error("generate-icons failed:", err);
  process.exit(1);
});
